version: '3.3'
services:
  backend:
    build: ./application
    container_name: cigarette_detector_backend
    volumes:
      - ./application/:/usr/src/application/
    expose:
      - 5090
    ports:
      - 5090:5090
    networks:
      - back_network


  frontend:
    build: ./frontend
    container_name: cigarette_detector_frontend
    tty: true
    expose:
      - 5091
    ports:
      - 5091:5091
    networks:
      - front_network

  nginx:
    build: ./nginx
    container_name: cigarette_detector_nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    networks:
      - back_network
      - front_network
    volumes:
      - ./frontend/:/usr/src/frontend/

networks:
  back_network:
    driver: bridge
  front_network:
    driver: bridge
